use crate::{lexer::IdentKind, parser::ExpectedFragment, span::Span, token::Token};

// FIXME: Overhaul this error type; most of the variants are just placeholders.
// FIXME: All errors should have spans
#[derive(Clone)]
#[cfg_attr(test, derive(Debug))]
pub enum Error {
    AbiStrSuffix(Span),
    AmbiguousPlus(Span),
    AutoTraitAlias,
    ChainedComparison(Span),
    DefaultOnInvalidItem(Span),
    EmptyCharLit(Span),
    EmptyExponent(Span),
    EmptyNumLit(Span),
    ExpectedTraitFoundTy(Span),
    FinalOnInvalidItem(Span),
    ForbiddenInnerAttrs,
    ForbiddenOuterAttrs,
    FrontmatterOpeningTooLarge(Span),
    GenericArgsOnFieldExpr(Span),
    HigherRankedBinderOnInvalidBound(Span),
    ImplRestrictedTraitAlias,
    InvalidAbiStr(Span),
    InvalidAssocItemKind(Span),
    InvalidDigit(Span),
    InvalidEscapeSequence(Span),
    InvalidExprPrefix(Span),
    InvalidExternItemKind(Span),
    InvalidExtraFieldProjections(Span),
    InvalidFrontmatterInfostring(Span),
    InvalidFrontmatterTrailer(Span),
    InvalidItemPrefix(Span),
    InvalidLetChain(Span),
    InvalidLitSuffix(Span),
    InvalidNumericIdent(Span),
    InvalidOpAfterBoundary(Span),
    InvalidOpAfterCast(Span),
    InvalidParenthesizedBound,
    InvalidRawIdent(IdentKind, Span),
    InvalidScalar(char, InvalidScalarPlace, Span),
    InvalidStrLitDelimiter(Span),
    InvalidTyPrefix(Span),
    LifetimeObjectTyWithoutPlus(Span),
    MisplacedReceiver(Span),
    MissingClosingDelimiters(Span),
    ModifiersOnInvalidBound,
    MultiScalarCharLit(Span),
    NonDecFloatLit(Span),
    ParametrizedWhereClause(Span),
    ParenthesizedGuardedPatInMatch,
    ReservedLabel(Span),
    ReservedLifetime(Span),
    ReservedMultiHash(Span),
    ReservedPrefix(Span),
    ReuseInherentImpl,
    StrLitGuardTooLarge(Span),
    TraitImplModifierInInherentImpl(&'static str),
    TyRelMacroCall(Span),
    UnexpectedClosingDelimiter(Token),
    UnexpectedToken(Token, ExpectedFragment),
    UnknownBuiltinSyntax(Span),
    UnsafeTraitAlias,
    UnterminatedBlockComment(Span),
    UnterminatedCharLit(Span),
    UnterminatedFrontmatter(Span),
    UnterminatedStrLit(Span),
    VisibilityOnInvalidItem(Span),
    TickFollowingRawTickedIdent(Span),
}

#[derive(Clone, Copy, Debug)]
pub enum InvalidScalarPlace {
    DocComment,
    File,
    FrontmatterBody,
    Lit,
}
