use crate::{lexer::IdentKind, parser::Fragment, span::Span, token::Token};
pub use utility::List1;

// FIXME: Overhaul this error type; most of the variants are just placeholders.
// FIXME: All errors should have spans
#[derive(Clone, Debug)]
pub enum Error {
    AbiStrSuffix(Span),
    AmbiguousPlus(Span),
    AutoTraitAlias(Span),
    ChainedComparison(Span),
    DefaultOnInvalidItem(Span),
    EmptyCharLit(Span),
    EmptyExponent(Span),
    EmptyNumLit(Span),
    ExpectedTraitFoundTy(Span),
    FinalOnInvalidItem(Span),
    ForbiddenInnerAttrs(Span),
    ForbiddenOuterAttrs(Span),
    FrontmatterOpeningTooLarge(Span),
    GenericArgsOnFieldExpr(Span),
    ImplRestrictedTraitAlias(Span),
    InvalidAbiStr(Span),
    InvalidAssocItemKind(Span),
    InvalidDigit(Span),
    InvalidEscapeSequence(Span),
    InvalidExprPrefix(Span),
    InvalidExternItemKind(Span),
    InvalidExtraFieldProjections(Span),
    InvalidFrontmatterInfostring(Span),
    InvalidFrontmatterTrailer(Span),
    InvalidItemPrefix(Span),
    InvalidLetChain(Span),
    InvalidLitSuffix(Span),
    InvalidNumericIdent(Span),
    InvalidOpAfterBoundary(Span),
    InvalidOpAfterCast(Span),
    InvalidRawIdent(IdentKind, Span),
    InvalidScalar(char, InvalidScalarPlace, Span),
    InvalidStrLitDelimiter(Span),
    InvalidTraitBoundModifier(Span),
    InvalidTyPrefix(Span),
    LifetimeObjectTyWithoutPlus(Span),
    MisplacedReceiver(Span),
    MissingClosingDelimiters(Span),
    MultiScalarCharLit(Span),
    NonDecFloatLit(Span),
    ParametrizedWhereClause(Span),
    ParenthesizedGuardedPatInMatch(Span),
    ReservedLabel(Span),
    ReservedLifetime(Span),
    ReservedMultiHash(Span),
    ReservedPrefix(Span),
    ReuseInherentImpl(Span),
    StrLitGuardTooLarge(Span),
    TraitImplModifierInInherentImpl(Span, &'static str),
    TyRelMacroCall(Span),
    UnexpectedClosingDelimiter(Token),
    UnexpectedToken(Token, List1<Fragment>),
    UnknownBuiltinSyntax(Span),
    UnsafeTraitAlias(Span),
    UnterminatedBlockComment(Span),
    UnterminatedCharLit(Span),
    UnterminatedFrontmatter(Span),
    UnterminatedStrLit(Span),
    VisibilityOnInvalidItem(Span),
    TickFollowingRawTickedIdent(Span),
}

#[derive(Clone, Copy, Debug)]
pub enum InvalidScalarPlace {
    DocComment,
    File,
    FrontmatterBody,
    Lit,
}
