[package]
name = "rasur"
version = "0.0.0-pre-alpha"
edition = "2024"
publish = false

[dependencies]
annotate-snippets = { git = "https://github.com/rust-lang/annotate-snippets-rs.git", rev = "74964e91d845e39fb549c4028452beffa7c6562b" }

