[package]
name = "rasur"
version.workspace = true
edition.workspace = true
publish = false

autotests = false

[lib]
path = "src/lib/lib.rs"

[dependencies]
unicode-ident = "=1.0.22"
utility = { path = "etc/lib/utility" }

[workspace]
members = ["etc/lib/utility","src/cli"]
default-members = ["src/cli"]

[workspace.package]
version = "0.0.0-pre-alpha"
edition = "2024"
