[package]
name = "rasur-cli"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "rasur-cli"
path = "main.rs"

[dependencies]
annotate-snippets = { git = "https://github.com/rust-lang/annotate-snippets-rs.git", rev = "74964e91d845e39fb549c4028452beffa7c6562b" }
clap = "4.5.58"
painter = { path = "../../etc/lib/painter" }
rasur = { path = "../.." }
utility = { path = "../../etc/lib/utility" }
