use crate::span::Span;
use std::fmt;

#[derive(Clone, Copy)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub(crate) const fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}

impl fmt::Debug for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let Self { kind, span } = self;

        write!(f, "{kind:?}@{span:?}")
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum TokenKind {
    //
    // Ident
    //
    // NOTE: Update `Self::is_ident` if you add a variant above this one.
    Abstract,
    As,
    Async,
    Await,
    Become,
    Box,
    Break,
    CommonIdent,
    Const,
    Continue,
    Crate,
    Do,
    Dyn,
    Else,
    Enum,
    Extern,
    False,
    Final,
    Fn,
    For,
    Gen,
    If,
    Impl,
    In,
    Let,
    Loop,
    Macro,
    Match,
    Mod,
    Move,
    Mut,
    Override,
    Priv,
    Pub,
    Ref,
    Return,
    SelfLower,
    SelfUpper,
    Static,
    Struct,
    Super,
    Trait,
    True,
    Try,
    Type,
    Typeof,
    Underscore,
    Unsafe,
    Use,
    Virtual,
    Where,
    While,
    // NOTE: Update `Self::is_ident` if you add a variant below this one!
    Yield,
    //
    // Other
    //
    AmpersandEquals,
    AsteriskEquals,
    At,
    BangEquals,
    CaretEquals,
    CharLit,
    CloseCurlyBracket,
    CloseRoundBracket,
    CloseSquareBracket,
    Comma,
    DoubleAmpersand,
    DoubleColon,
    DoubleDot,
    DoubleDotEquals,
    DoubleEquals,
    DoubleGreaterThan,
    DoubleGreaterThanEquals,
    DoubleLessThan,
    DoubleLessThanEquals,
    DoublePipe,
    EndOfInput,
    Error,
    GreaterThanEquals,
    Hash,
    HypenEquals,
    Invalid,
    LessThanEquals,
    NumLit,
    OpenCurlyBracket,
    OpenRoundBracket,
    OpenSquareBracket,
    PercentEquals,
    PipeEquals,
    PlusEquals,
    QuestionMark,
    Semicolon,
    SingleAmpersand,
    SingleAsterisk,
    SingleBang,
    SingleCaret,
    SingleColon,
    SingleDot,
    SingleEquals,
    SingleGreaterThan,
    SingleHyphen,
    SingleLessThan,
    SinglePercent,
    SinglePipe,
    SinglePlus,
    SingleSlash,
    SlashEquals,
    StrLit,
    ThinArrow,
    TickedIdent,
    TripleDot,
    Trivia,
    WideArrow,
    InnerDocComment,
    OuterDocComment,
}

impl TokenKind {
    pub(crate) fn is_ident(self) -> bool {
        Self::Abstract as u8 <= self as u8 && self as u8 <= Self::Yield as u8
    }

    pub fn repr(self) -> Repr {
        match self {
            Self::Abstract => Repr::Src("abstract"),
            Self::AmpersandEquals => Repr::Src("&="),
            Self::As => Repr::Src("as"),
            Self::AsteriskEquals => Repr::Src("*="),
            Self::Async => Repr::Src("async"),
            Self::At => Repr::Src("@"),
            Self::Await => Repr::Src("await"),
            Self::BangEquals => Repr::Src("!="),
            Self::Become => Repr::Src("become"),
            Self::Box => Repr::Src("box"),
            Self::Break => Repr::Src("break"),
            Self::CaretEquals => Repr::Src("^="),
            Self::CharLit => Repr::Tag("char literal"),
            Self::CloseCurlyBracket => Repr::Src("}"),
            Self::CloseRoundBracket => Repr::Src(")"),
            Self::CloseSquareBracket => Repr::Src("]"),
            Self::Comma => Repr::Src(","),
            Self::CommonIdent => Repr::Tag("common identifier"),
            Self::Const => Repr::Src("const"),
            Self::Continue => Repr::Src("continue"),
            Self::Crate => Repr::Src("crate"),
            Self::Do => Repr::Src("do"),
            Self::DoubleAmpersand => Repr::Src("&&"),
            Self::DoubleColon => Repr::Src("::"),
            Self::DoubleDot => Repr::Src(".."),
            Self::DoubleDotEquals => Repr::Src("..="),
            Self::DoubleEquals => Repr::Src("=="),
            Self::DoubleGreaterThan => Repr::Src(">>"),
            Self::DoubleGreaterThanEquals => Repr::Src(">>="),
            Self::DoubleLessThan => Repr::Src("<<"),
            Self::DoubleLessThanEquals => Repr::Src("<<="),
            Self::DoublePipe => Repr::Src("||"),
            Self::Dyn => Repr::Src("dyn"),
            Self::Else => Repr::Src("else"),
            Self::EndOfInput => Repr::Tag("end of input"),
            Self::Enum => Repr::Src("enum"),
            Self::Error => Repr::Tag("error"),
            Self::Extern => Repr::Src("extern"),
            Self::False => Repr::Src("false"),
            Self::Final => Repr::Src("final"),
            Self::Fn => Repr::Src("fn"),
            Self::For => Repr::Src("for"),
            Self::Gen => Repr::Src("gen"),
            Self::GreaterThanEquals => Repr::Src(">="),
            Self::Hash => Repr::Src("#"),
            Self::HypenEquals => Repr::Src("-="),
            Self::If => Repr::Src("if"),
            Self::Impl => Repr::Src("impl"),
            Self::In => Repr::Src("in"),
            Self::Invalid => Repr::Tag("invalid"),
            Self::LessThanEquals => Repr::Src("`<=`"),
            Self::Let => Repr::Src("let"),
            Self::Loop => Repr::Src("loop"),
            Self::Macro => Repr::Src("macro"),
            Self::Match => Repr::Src("match"),
            Self::Mod => Repr::Src("mod"),
            Self::Move => Repr::Src("move"),
            Self::Mut => Repr::Src("mut"),
            Self::NumLit => Repr::Tag("number literal"),
            Self::OpenCurlyBracket => Repr::Src("{"),
            Self::OpenRoundBracket => Repr::Src("("),
            Self::OpenSquareBracket => Repr::Src("["),
            Self::Override => Repr::Src("override"),
            Self::PercentEquals => Repr::Src("%="),
            Self::PipeEquals => Repr::Src("|="),
            Self::PlusEquals => Repr::Src("+="),
            Self::Priv => Repr::Src("priv"),
            Self::Pub => Repr::Src("pub"),
            Self::QuestionMark => Repr::Src("?"),
            Self::Ref => Repr::Src("ref"),
            Self::Return => Repr::Src("return"),
            Self::SelfLower => Repr::Src("self"),
            Self::SelfUpper => Repr::Src("Self"),
            Self::Semicolon => Repr::Src(";"),
            Self::SingleAmpersand => Repr::Src("&"),
            Self::SingleAsterisk => Repr::Src("*"),
            Self::SingleBang => Repr::Src("!"),
            Self::SingleCaret => Repr::Src("^"),
            Self::SingleColon => Repr::Src(":"),
            Self::SingleDot => Repr::Src("."),
            Self::SingleEquals => Repr::Src("="),
            Self::SingleGreaterThan => Repr::Src(">"),
            Self::SingleHyphen => Repr::Src("-"),
            Self::SingleLessThan => Repr::Src("<"),
            Self::SinglePercent => Repr::Src("%"),
            Self::SinglePipe => Repr::Src("|"),
            Self::SinglePlus => Repr::Src("+"),
            Self::SingleSlash => Repr::Src("/"),
            Self::SlashEquals => Repr::Src("/="),
            Self::Static => Repr::Src("static"),
            Self::StrLit => Repr::Tag("string literal"),
            Self::Struct => Repr::Src("struct"),
            Self::Super => Repr::Src("super"),
            Self::ThinArrow => Repr::Src("->"),
            Self::TickedIdent => Repr::Tag("ticked identifier"),
            Self::Trait => Repr::Src("trait"),
            Self::TripleDot => Repr::Src("..."),
            Self::Trivia => Repr::Tag("trivia"),
            Self::True => Repr::Src("true"),
            Self::Try => Repr::Src("try"),
            Self::Type => Repr::Src("type"),
            Self::Typeof => Repr::Src("typeof"),
            Self::Underscore => Repr::Src("_"),
            Self::Unsafe => Repr::Src("unsafe"),
            Self::Use => Repr::Src("use"),
            Self::Virtual => Repr::Src("virtual"),
            Self::Where => Repr::Src("where"),
            Self::While => Repr::Src("while"),
            Self::WideArrow => Repr::Src("=>"),
            Self::Yield => Repr::Src("yield"),
            Self::InnerDocComment => Repr::Tag("inner doc comment"),
            Self::OuterDocComment => Repr::Tag("outer doc comment"),
        }
    }
}

pub enum Repr {
    Src(&'static str),
    Tag(&'static str),
}

pub(crate) macro PathSegKeyword() {
    TokenKind::SelfLower | TokenKind::Super | TokenKind::Crate | TokenKind::SelfUpper
}

pub(crate) macro PathSegIdent() {
    PathSegKeyword!() | TokenKind::CommonIdent
}
